# Generated by Django 6.0.3 on 2026-04-16 22:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewo', '0002_workday_and_line_reparent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraworkorder',
            name='equip_mat_ohp_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1500'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Equipment & Materials OH&P %'),
        ),
        migrations.AlterField(
            model_name='extraworkorder',
            name='labor_ohp_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1500'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Labor OH&P %'),
        ),
        migrations.AlterField(
            model_name='historicalextraworkorder',
            name='equip_mat_ohp_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1500'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Equipment & Materials OH&P %'),
        ),
        migrations.AlterField(
            model_name='historicalextraworkorder',
            name='labor_ohp_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1500'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Labor OH&P %'),
        ),
        migrations.AlterField(
            model_name='historicalworkday',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkday',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
