# Generated by Django 6.0.3 on 2026-04-16 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewo', '0003_alter_extraworkorder_equip_mat_ohp_pct_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workday',
            options={'ordering': ['ewo', 'work_date', 'id'], 'verbose_name': 'Work Day', 'verbose_name_plural': 'Work Days'},
        ),
        migrations.RemoveConstraint(
            model_name='workday',
            name='unique_workday_per_ewo_date',
        ),
    ]
