# Generated by Django 6.0.3 on 2026-04-16 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caltransrateline',
            name='overtime_rate',
        ),
        migrations.RemoveField(
            model_name='caltransrateline',
            name='rw_delay_rate',
        ),
        migrations.RemoveField(
            model_name='historicalcaltransrateline',
            name='overtime_rate',
        ),
        migrations.RemoveField(
            model_name='historicalcaltransrateline',
            name='rw_delay_rate',
        ),
        migrations.AddField(
            model_name='caltransrateline',
            name='ot_factor',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='caltransrateline',
            name='rw_delay_factor',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='ct_match_quality',
            field=models.CharField(choices=[('exact', 'Exact'), ('close', 'Close'), ('none', 'No Match'), ('retired', 'CT Code Retired'), ('fmv', 'Fair Market Value')], default='none', help_text='Provenance of the rates — documents defensibility in claims.', max_length=10),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='fuel_surcharge_eligible',
            field=models.BooleanField(default=True, help_text='Whether this equipment type participates in the fuel surcharge pool.'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='rate_ot',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Overtime rate ($/hr).', max_digits=8),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='rate_reg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Operating rate ($/hr).', max_digits=8),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='rate_standby',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Standby (RW delay) rate ($/hr).', max_digits=8),
        ),
        migrations.AddField(
            model_name='historicalcaltransrateline',
            name='ot_factor',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='historicalcaltransrateline',
            name='rw_delay_factor',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='historicalequipmenttype',
            name='ct_match_quality',
            field=models.CharField(choices=[('exact', 'Exact'), ('close', 'Close'), ('none', 'No Match'), ('retired', 'CT Code Retired'), ('fmv', 'Fair Market Value')], default='none', help_text='Provenance of the rates — documents defensibility in claims.', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalequipmenttype',
            name='fuel_surcharge_eligible',
            field=models.BooleanField(default=True, help_text='Whether this equipment type participates in the fuel surcharge pool.'),
        ),
        migrations.AddField(
            model_name='historicalequipmenttype',
            name='rate_ot',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Overtime rate ($/hr).', max_digits=8),
        ),
        migrations.AddField(
            model_name='historicalequipmenttype',
            name='rate_reg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Operating rate ($/hr).', max_digits=8),
        ),
        migrations.AddField(
            model_name='historicalequipmenttype',
            name='rate_standby',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Standby (RW delay) rate ($/hr).', max_digits=8),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='caltrans_rate_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_types', to='resources.caltransrateline'),
        ),
    ]
