# Generated by Django 6.0.3 on 2026-04-16 21:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_caltrans_factors_and_equipmenttype_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caltransrateline',
            name='ot_factor',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='caltransrateline',
            name='rw_delay_factor',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='historicalcaltransrateline',
            name='ot_factor',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='historicalcaltransrateline',
            name='rw_delay_factor',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
    ]
