# Generated by Django 6.0.3 on 2026-04-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_caltransrateline_ot_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='historicalequipmenttype',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalequipmenttype',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
